Tuple1=(1,2,3,4,5,0,3,4)
Tuple2=('a','b','c','d','e')
print (max(Tuple1))
print (min(Tuple1))
print (sum(Tuple1))
print (len(Tuple1))
a=Tuple1.index(4)
print (a)
b=Tuple1.count(1)
print (b)
print (sorted(Tuple1))
#print (sort(Tuple1))
print (Tuple1) 
print (Tuple1+Tuple2)
print (Tuple1*2)
print(Tuple1[3:6])
print(Tuple1[:3])
print (all(Tuple1))
print (any(Tuple1))
print (all(Tuple2))
print (any(Tuple2))